In [1]:
pip install pyarrow

Requirement already satisfied: pyarrow in /Users/pji/anaconda3/lib/python3.11/site-packages (11.0.0)
Requirement already satisfied: numpy>=1.16.6 in /Users/pji/anaconda3/lib/python3.11/site-packages (from pyarrow) (1.24.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
data1 = pd.read_parquet("advanced.parq")
data2 = pd.read_csv("all_seasons.csv")

In [4]:
print(data1)

       Rk              Player  Age   G    MP   PER    TS%   3PAr    FTr  ORB%  \
0       1  Christian Laettner   25  81  2770  17.7  0.580  0.043  0.543   7.3
1       2        Isaiah Rider   23  75  2645  15.6  0.548  0.317  0.271   4.2
2       3          Sean Rooks   25  80  2405  12.6  0.555  0.008  0.620   8.5
3       4           Doug West   27  71  2328  11.6  0.528  0.080  0.323   3.2
4       5     Winston Garland   30  73  1931  10.1  0.488  0.183  0.273   3.1
...    ..                 ...  ...  ..   ...   ...    ...    ...    ...   ...
12621  20  Jeenathan Williams   23   5   127  15.5  0.657  0.205  0.077   9.0
12622  21  Shaquille Harrison   29   5   120  17.9  0.516  0.278  0.417   1.0
12623  22      Greg Brown III   21  16    93   5.8  0.421  0.250  0.429   2.5
12624  23       Justin Minaya   23   4    89   4.0  0.363  0.522  0.043   3.8
12625  24     Chance Comanche   26   1    21  12.2  0.518  0.000  0.800  10.9

       ...   WS  WS/48  Unnamed: 22  OBPM  DBPM  BPM  VORP  team     season  \
0      ...  6.2  0.108          NaN   0.7   0.4  1.1   2.2   MIN  1995/1996
1      ...  1.9  0.034          NaN   2.0  -2.5 -0.5   1.0   MIN  1995/1996
2      ...  3.0  0.060          NaN  -1.5  -1.5 -3.0  -0.6   MIN  1995/1996
3      ...  1.8  0.038          NaN  -2.2  -1.2 -3.4  -0.8   MIN  1995/1996
4      ...  1.2  0.030          NaN  -2.2  -0.3 -2.6  -0.3   MIN  1995/1996
...    ...  ...    ...          ...   ...   ...  ...   ...   ...        ...
12621  ...  0.3  0.120          NaN  -1.0  -2.1 -3.0   0.0   POR  2023/2024
12622  ...  0.3  0.137          NaN  -2.5   2.6  0.1   0.1   POR  2023/2024
12623  ... -0.1 -0.074          NaN  -8.5   0.0 -8.5  -0.2   POR  2023/2024
12624  ... -0.1 -0.067          NaN  -7.2  -1.9 -9.0  -0.2   POR  2023/2024
12625  ...  0.0  0.043          NaN  -2.6  -4.9 -7.5   0.0   POR  2023/2024

       team_retcon
0              MIN
1              MIN
2              MIN
3              MIN
4              MIN
...            ...
12621          POR
12622          POR
12623          POR
12624          POR
12625          POR

[12626 rows x 30 columns]

In [5]:
data1

,Rk,Player,Age,G,MP,PER,TS%,3PAr,FTr,ORB%,...,WS,WS/48,Unnamed: 22,OBPM,DBPM,BPM,VORP,team,season,team_retcon
0,1,Christian Laettner,25,81,2770,17.7,0.580,0.043,0.543,7.3,...,6.2,0.108,NaN,0.7,0.4,1.1,2.2,MIN,1995/1996,MIN
1,2,Isaiah Rider,23,75,2645,15.6,0.548,0.317,0.271,4.2,...,1.9,0.034,NaN,2.0,-2.5,-0.5,1.0,MIN,1995/1996,MIN
2,3,Sean Rooks,25,80,2405,12.6,0.555,0.008,0.620,8.5,...,3.0,0.060,NaN,-1.5,-1.5,-3.0,-0.6,MIN,1995/1996,MIN
3,4,Doug West,27,71,2328,11.6,0.528,0.080,0.323,3.2,...,1.8,0.038,NaN,-2.2,-1.2,-3.4,-0.8,MIN,1995/1996,MIN
4,5,Winston Garland,30,73,1931,10.1,0.488,0.183,0.273,3.1,...,1.2,0.030,NaN,-2.2,-0.3,-2.6,-0.3,MIN,1995/1996,MIN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12621,20,Jeenathan Williams,23,5,127,15.5,0.657,0.205,0.077,9.0,...,0.3,0.120,NaN,-1.0,-2.1,-3.0,0.0,POR,2023/2024,POR
12622,21,Shaquille Harrison,29,5,120,17.9,0.516,0.278,0.417,1.0,...,0.3,0.137,NaN,-2.5,2.6,0.1,0.1,POR,2023/2024,POR
12623,22,Greg Brown III,21,16,93,5.8,0.421,0.250,0.429,2.5,...,-0.1,-0.074,NaN,-8.5,0.0,-8.5,-0.2,POR,2023/2024,POR
12624,23,Justin Minaya,23,4,89,4.0,0.363,0.522,0.043,3.8,...,-0.1,-0.067,NaN,-7.2,-1.9,-9.0,-0.2,POR,2023/2024,POR
12625,24,Chance Comanche,26,1,21,12.2,0.518,0.000,0.800,10.9,...,0.0,0.043,NaN,-2.6,-4.9,-7.5,0.0,POR,2023/2024,POR

In [8]:
data1["season"] = data1["season"].str.replace("/", "-")

In [10]:
data1.head()

,Rk,Player,Age,G,MP,PER,TS%,3PAr,FTr,ORB%,...,WS,WS/48,Unnamed: 22,OBPM,DBPM,BPM,VORP,team,season,team_retcon
0,1,Christian Laettner,25,81,2770,17.7,0.580,0.043,0.543,7.3,...,6.2,0.108,NaN,0.7,0.4,1.1,2.2,MIN,1995-1996,MIN
1,2,Isaiah Rider,23,75,2645,15.6,0.548,0.317,0.271,4.2,...,1.9,0.034,NaN,2.0,-2.5,-0.5,1.0,MIN,1995-1996,MIN
2,3,Sean Rooks,25,80,2405,12.6,0.555,0.008,0.620,8.5,...,3.0,0.060,NaN,-1.5,-1.5,-3.0,-0.6,MIN,1995-1996,MIN
3,4,Doug West,27,71,2328,11.6,0.528,0.080,0.323,3.2,...,1.8,0.038,NaN,-2.2,-1.2,-3.4,-0.8,MIN,1995-1996,MIN
4,5,Winston Garland,30,73,1931,10.1,0.488,0.183,0.273,3.1,...,1.2,0.030,NaN,-2.2,-0.3,-2.6,-0.3,MIN,1995-1996,MIN

In [11]:
data2 = data2.rename(columns={"player_name": "Player"})

data2

,Unnamed: 0,Player,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,0,Randy Livingston,HOU,22.0,193.04,94.800728,Louisiana State,USA,1996,2,...,3.9,1.5,2.4,0.3,0.042,0.071,0.169,0.487,0.248,1996-97
1,1,Gaylon Nickerson,WAS,28.0,190.50,86.182480,Northwestern Oklahoma,USA,1994,2,...,3.8,1.3,0.3,8.9,0.030,0.111,0.174,0.497,0.043,1996-97
2,2,George Lynch,VAN,26.0,203.20,103.418976,North Carolina,USA,1993,1,...,8.3,6.4,1.9,-8.2,0.106,0.185,0.175,0.512,0.125,1996-97
3,3,George McCloud,LAL,30.0,203.20,102.058200,Florida State,USA,1989,1,...,10.2,2.8,1.7,-2.7,0.027,0.111,0.206,0.527,0.125,1996-97
4,4,George Zidek,DEN,23.0,213.36,119.748288,UCLA,USA,1995,1,...,2.8,1.7,0.3,-14.1,0.102,0.169,0.195,0.500,0.064,1996-97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12839,12839,Joel Embiid,PHI,29.0,213.36,127.005760,Kansas,Cameroon,2014,1,...,33.1,10.2,4.2,8.8,0.057,0.243,0.370,0.655,0.233,2022-23
12840,12840,John Butler Jr.,POR,20.0,213.36,86.182480,Florida State,USA,Undrafted,Undrafted,...,2.4,0.9,0.6,-16.1,0.012,0.065,0.102,0.411,0.066,2022-23
12841,12841,John Collins,ATL,25.0,205.74,102.511792,Wake Forest,USA,2017,1,...,13.1,6.5,1.2,-0.2,0.035,0.180,0.168,0.593,0.052,2022-23
12842,12842,Jericho Sims,NYK,24.0,208.28,113.398000,Texas,USA,2021,2,...,3.4,4.7,0.5,-6.7,0.117,0.175,0.074,0.780,0.044,2022-23
12843,12843,JaMychal Green,GSW,33.0,205.74,102.965384,Alabama,USA,Undrafted,Undrafted,...,6.4,3.6,0.9,-8.2,0.087,0.164,0.169,0.650,0.094,2022-23

In [13]:
# merged_df = pd.merge(data1, data2, on=["Player"])

merged_df = data2.merge(data1, on=["Player", "season"], how="outer")

# merged_df = merged_df.drop_duplicates(subset=["Player", "Season"]) -- try this if there are additional duplicates

merged_df.sample(20)

,Unnamed: 0,Player,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,DWS,WS,WS/48,Unnamed: 22,OBPM,DBPM,BPM,VORP,team,team_retcon
15842,NaN,James Blackwell,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.104,NaN,-1.6,2.9,1.3,0.0,CHH,CHO
18051,NaN,Brad Miller,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.6,2.6,0.091,NaN,0.7,-0.2,0.5,0.8,SAC,SAC
9298,9298.0,Shabazz Muhammad,MIN,24.0,198.12,101.151016,UCLA,USA,2013,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5963,5963.0,Eduardo Najera,DAL,33.0,203.20,106.594120,Oklahoma,Mexico,2000,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4982,4982.0,Jacque Vaughn,SAS,33.0,185.42,86.182480,Kansas,USA,1997,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12352,12352.0,Moses Moody,GSW,21.0,195.58,95.707912,Arkansas,USA,2021,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10906,10906.0,Elfrid Payton,NYK,26.0,190.50,88.450440,Louisana-Lafayette,USA,2014,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20839,NaN,Tobias Harris,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.7,4.1,0.107,NaN,0.0,-0.7,-0.7,0.6,ORL,ORL
14905,NaN,Wesley Matthews,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.9,4.6,0.108,NaN,-0.6,0.0,-0.5,0.8,UTA,UTA
16945,NaN,Ronny Turiaf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.1,4.2,0.137,NaN,-1.2,1.9,0.7,1.0,LAL,LAL
1328,1328.0,Michael Curry,DET,31.0,195.58,102.965384,Georgia Southern,USA,Undrafted,Undrafted,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17176,NaN,Kostas Antetokounmpo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.1,0.193,NaN,0.2,-0.9,-0.7,0.0,LAL,LAL
16407,NaN,Jeremy Lamb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.8,2.7,0.099,NaN,-1.1,0.8,-0.4,0.5,IND,IND
13053,NaN,Troy Hudson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.4,0.7,0.042,NaN,-0.1,-2.0,-2.1,0.0,MIN,MIN
20142,NaN,Josh Powell,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.4,0.7,0.079,NaN,-2.7,-0.9,-3.6,-0.2,DAL,DAL
16170,NaN,Stephen Jackson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.9,4.4,0.073,NaN,-0.6,0.5,-0.1,1.4,IND,IND
1167,1167.0,Vince Carter,TOR,22.0,200.66,97.522280,North Carolina,USA,1998,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19721,NaN,Jimmy Butler,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.6,7.1,0.131,NaN,-0.9,2.0,1.1,2.0,CHI,CHI
21226,NaN,Matt Barnes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.4,1.0,0.090,NaN,-3.1,-0.3,-3.4,-0.2,PHI,PHI
14914,NaN,Kosta Koufos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.2,0.0,0.014,NaN,-5.3,-1.2,-6.5,-0.2,UTA,UTA

In [15]:
clean_data = merged_df.dropna(subset=["age"])

In [18]:
clean_data.columns

Index(['Unnamed: 0', 'Player', 'team_abbreviation', 'age', 'player_height',
       'player_weight', 'college', 'country', 'draft_year', 'draft_round',
       'draft_number', 'gp', 'pts', 'reb', 'ast', 'net_rating', 'oreb_pct',
       'dreb_pct', 'usg_pct', 'ts_pct', 'ast_pct', 'season', 'Rk', 'Age', 'G',
       'MP', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%',
       'STL%', 'BLK%', 'TOV%', 'USG%', 'Unnamed: 17', 'OWS', 'DWS', 'WS',
       'WS/48', 'Unnamed: 22', 'OBPM', 'DBPM', 'BPM', 'VORP', 'team',
       'team_retcon'],
      dtype='object')